name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Use an official Crystal Docker image so we have crystal + shards available
    container: crystallang/crystal:1.18.2
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Format check
        run: crystal tool format --check
      - name: Run linter (ameba)
        run: shards exec ameba
      - name: Run specs
        run: crystal spec
